version: "3"
services:
  microservice-config-server:
    image: microservice-config-server
    ports:
      - "8888:8888"

  microservice-eureka:
    image: microservice-eureka
    ports:
      - "8761:8761"
    depends_on:
      - microservice-config-server

  microservice-api-gateway:
    image: microservice-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - microservice-config-server

  microservice-product:
    image: microservice-product
    ports:
      - "8090:8090"
    depends_on:
      - microservice-config-server
      - microservice-eureka
      - microservice-product-db

  microservice-product-db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/docker-volumes/personal/microservices/product:/var/lib/postgresql
    ports:
      - '5550:5432'

  microservice-inventory:
    image: microservice-inventory
    ports:
      - "8091:8091"
    depends_on:
      - microservice-config-server
      - microservice-eureka
      - microservice-inventory-db

  microservice-inventory-db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/docker-volumes/personal/microservices/inventory:/var/lib/postgresql
    ports:
      - '6660:5432'