server:
  port: 8091

spring:
  application:
    name: ms-inventory
  config:
    import: optional:configserver:http://microservice-config-server:8888
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 200
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        generate_statistics: true
  datasource:
    url: jdbc:postgresql://microservice-inventory-db:5432/postgres
    username: postgres
    password: postgres
    hikari:
      data-source-properties.stringtype: unspecified
      tomcat:
        connection-properties: stringtype=unspecified

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://microservice-eureka:8761/eureka
